### ISSUE TITLE
DevEnvironment - Setup Database

### ISSUE THREAD

**Issue by makakken** [konglomerat/roseguarden#17]
Hallo, wie bekomme ich denn einen admin-User zum laufen? Gibts da nen Trick, oder steht da schon einer in der DB wenn ich die Migrations laufen lasse? Ich wollte mal die anderen Pages im Admin backend anschuaen und guggen was evtl. an vue-packages rauskann, oder wo ich kleine layoutverbesserungen reinbasteln kann. hab aber keine ahnung ob ich im menü schon alles sehe etc.

**Comment by mdrobisch** [comment]
Der Admin User wird beim erstmaligen ausführen von Flask erstellt. 
Dort wird in der `create_devEnv` alles notwendige für die Entwicklungs angelegt (Spaces, Nodes, User, Rechte)
Siehe: https://github.com/konglomerat/roseguarden/blob/master/backend/devEnv.py

Standard-Admin: `admin@fabba.space` : `admin1234`
Standard-User: `roseguarden@fabba.space` : `test1234`

**Comment by makakken** [comment]
👍 habs gesehen nachdem ich mir die DB angesehen hab... einfach nutzer registrieren und admin und authenticated auf true setzen geht auch ;)
