### ISSUE TITLE
Github Fehler Tickets ohne anmeldung erstellen

### ISSUE THREAD

**Issue by stephanfriedrich** [konglomerat/roseguarden#19]
Hintergrund hier ist, dass ohne einen Githubaccount keine Fehler-Tickets erstellt werden können.

**Comment by mdrobisch** [comment]
Github bietet das nicht an. D.h. es gibt keine Schnittstelle dafür.
Workarround siehe hier: https://gitreports.com/ wäre möglich

**Comment by stephanfriedrich** [comment]
Ist soweit eingerichtet und der Link in der Vue-App angepasst.
