### ISSUE TITLE
Datenschutz Link auf Startseite - 404

### ISSUE THREAD

**Issue by stephanfriedrich** [konglomerat/roseguarden#26]
Submitter: frido
Leider funktioniert der Datenschutz Link nicht von der startseite weg, da lädt er nur sehr lange "https://open.konglomerat.org/dashboard"

**Comment by makakken** [comment]
Erstmal auf eine statische Seite die gültig ist weiterleiten (/datenschutz) im späteren verlauf villeicht ne config-Option?

**Comment by makakken** [comment]
also im live-system gehts... daher: close!
