### ISSUE TITLE
[FEATURE] FAQ hinzufügen

### ISSUE THREAD

**Issue by stephanfriedrich** [konglomerat/roseguarden#3]
Als Benutzer möchte ich häufig gestellte Fragen als Hilfe nutzen können.

**Comment by mdrobisch** [comment]
Fixed in #14

**Comment by mdrobisch** [comment]
Bitte selber schließen, wenn das für dich soweit passt

**Comment by stephanfriedrich** [comment]
Ist jetzt drin
