### ISSUE TITLE
E-Mail Verifizierungs Timeout erhöhen

### ISSUE THREAD

**Issue by stephanfriedrich** [konglomerat/roseguarden#32]
Als anmeldender Benutzer möchte ich, dass der E-Mail Verifizierungslink etwas länger valide ist.

**Comment by mdrobisch** [comment]
@stephanfriedrich  : Wie lange soll er valide sein? Aktuell sind es 24h.

**Comment by makakken** [comment]
können wir da ne woche draus machen? fänd ich sinnvoll... auf jeden fall mindestens 48h...

**Comment by makakken** [comment]
sind jetzt 72h
