### ISSUE TITLE
Kritisch: Nicht verifizierter Nutzer kann Tür öffnen

### ISSUE THREAD

**Issue by stephanfriedrich** [konglomerat/roseguarden#37]
Ganz konkreter Fall: USER_B hat sich registriert aber nicht verifiziert. So steht es im System. Kommt aber trotzdem rein mit ihrer Karte. Das sollte, wenn ich das richtig versteh ja eigentlich nicht so sein. Oder passiert dies weil sie einen unlimitierten Zugang hat?

**Comment by makakken** [comment]
@mdrobisch kannst du das bitte mal prüfen und fixen? Das würde ic hals kritisch einstufen!
