### ISSUE TITLE
[BUGFIX] Fehlendes Submenu-Icon

### ISSUE THREAD

**Issue by stephanfriedrich** [konglomerat/roseguarden#4]
![Bildschirmfoto zu 2021-03-23 22-16-32](https://user-images.githubusercontent.com/2052955/112219620-8cde7580-8c25-11eb-9e92-d06b093bfc31.png)

**Comment by stephanfriedrich** [comment]
wurde nur von meinem Browser geblockt, da hier externe Assets eingebunden werden

**Comment by mdrobisch** [comment]
👍
