### ISSUE TITLE
Benutzerauthentifizierung per Karte im Backend verändern

### ISSUE THREAD

**Issue by makakken** [konglomerat/roseguarden#43]
Aktuell wird die Karten_ID mit bcrypt gehasht gespeichert. Da wir aber zum öffnen der Türen keinen anderen Wert als die Karten_ID haben um die Datenbank nach Nutzen zu durchsuchen, muss zwangsläufig viel gehasht werden. bcrypt ist hier per DESIGN extrem langsam (Um Brute-Force Attaacs zu verhindern). Das Problem, eine For-Each Schleife mit Bcrypt ist quasi einer brute-force Attacke gleich. Das heißt, je mehr Benutzer, desto länger dauert die Authentifizierung.

Im aktuell implementierten Kontext sag ich mal: failure by design 🚀 

Ich habe zwei zu diskutierende Vorschläge:
1. einfach statt bcrypt md5 oder sha512 (jeweils mit SALT) nehmen, sollte deutlich schneller sein und ein select by Karten_ID währe auf der Datenbank wieder möglich.
2. Es braucht bei der Verifizierung einer Karte zusätzliche Sicherheitsmerkmale auf der Karte. Beispielsweise die User-UUID. (Die Karten_ID ist ja eh drauf) Dann kann man erst in der Datenbank anch UserUUID selecten, und dann mit bcrypt die Karten_ID prüfen.

**Comment by makakken** [comment]
Ich bin übrigens für 1tens. 
Pros:
- Ist in vielen Projekten die ich kenne Standard. 
- eine Karten_ID stellt für mich kein besonders zu schützendes Datum dar.
- Ist immerhin die KartenID nicht im Klartext gespeichert

Kons:
- Es braucht einen neuen Brute-Force Schutz
- Es braucht eine Config in welche wir einen SALT legen können um es Angreifern in besitz der Datenbank nciht viel zu einfach zu machen.

**Comment by mdrobisch** [comment]
Should be fixed by the session today.
Should be closed after some time in production to wait for regressions.

**Comment by makakken** [comment]
der remindr bot hat nciht funktioniert ;) ich schließ das jetzt mal...
