### ISSUE TITLE
Layout Problem in Data-Table / Auswahl Anzahl Datensätze

### ISSUE THREAD

**Issue by stephanfriedrich** [konglomerat/roseguarden#46]
Submitter: Bettina Weber
im Bereich user access kann ich unten auswählen wieviele personen es anzeigen soll 15 oder 30 oder alle. der alle button verschwindet aber bei mir immer in der leiste...bug oder ich?

**Comment by makakken** [comment]
Die AUswahl wieviele Datensätze angezeigt werden sollen, verschwindet hinter der FOOTER-Leist

<img width="1177" alt="Bildschirmfoto 2021-09-29 um 10 22 09" src="https://user-images.githubusercontent.com/10586572/135230964-283c51b3-d5ff-41dd-9cf5-3959c6c84318.png">
e.
