### ISSUE TITLE
[TODO] Cleanup code

### ISSUE THREAD

**Issue by stephanfriedrich** [konglomerat/roseguarden#7]
Im master der PWA, ind verschiedene Probleme im Quellcode aufgefallen.

* es gibt verschiedene Code-Style Abweichungen
* es finden sich überall auskommentierer Code 
* es gibt es hardcoded Testsystem Konfigs (Benutzer und Passwörter)
* Die Pfade für das PWA Routing scheinen mir auch nicht konsistenz umgesetzt zu sein. Dh. diese sind anverschiedensten Stellen angegeben 

Der Code brauch also eine grundlegende aufräum aktion.

**Comment by mdrobisch** [comment]
Meiner Meinung nach ist es nicht sinnvoll allgemeine Probleme wie Code-Cleanup oder Refactoring als Issue zu pflegen. 
Diese müssen im Entwicklungsprozess gelöst werden. Z.B. per Review.  Problem dabei ist, das solche Ticket im Worst-Case nie geschlossen werden und vom wesentlichen Ablenken.

Vorschlag einfach als Pull-Request Änderungen vorschlagen und das Ticket schließen.

**Comment by mdrobisch** [comment]
Weiterer Vorschlag. Bitte mit dem Github Labeln arbeiten. Tags in der Überschrift wie "[TODO]" oder "[FEATURE]" lassen sich so noch besser abbilden.
